export { GeneralSection } from './General'
export { AvatarSection } from './Avatar'
export { StatusSection } from './Status'
export { RoleSection } from './Role'
export { PasswordSection } from './Password'
